### ISSUE TITLE
Tracking Module

### ISSUE THREAD

**Issue by therealjendavis** [therealjendavis/checklist#7]
- [ ] The Orbital Probe Cannon has launched millions of probes.
- [ ] The 9 ,318 ,054th probe located a deep space anomaly matching all known criteria for the Eye of the universe.
- [x] The Probe Tracking Module automatically records each probe’s trajectory and transmits the data to the Ash Twin Project.
- [x] I found Nomai coordinates marking the location of the Eye of the universe.
